const PDFDocument =
  require("pdfkit");

const fs =
  require("fs");

const path =
  require("path");

/*
====================================
GENERATE PDF REPORT
====================================
*/

exports.generatePDFReport =
  async (
    reportData,
    reportName
  ) => {
    return new Promise(
      (
        resolve,
        reject
      ) => {
        /*
        REPORT PATH
        */

        const reportsDir =
          path.join(
            __dirname,
            "../reports"
          );

        /*
        CREATE DIR
        */

        if (
          !fs.existsSync(
            reportsDir
          )
        ) {
          fs.mkdirSync(
            reportsDir
          );
        }

        /*
        FILE PATH
        */

        const filePath =
          path.join(
            reportsDir,

            `${reportName}.pdf`
          );

        /*
        DOC
        */

        const doc =
          new PDFDocument({
            margin: 50,
          });

        /*
        STREAM
        */

        const stream =
          fs.createWriteStream(
            filePath
          );

        doc.pipe(stream);

        /*
        HEADER
        */

        doc
          .fontSize(24)
          .text(
            "AI Competency Report",
            {
              align:
                "center",
            }
          );

        doc.moveDown();

        /*
        CANDIDATE
        */

        doc
          .fontSize(18)
          .text(
            "Candidate Information"
          );

        doc.moveDown(0.5);

        doc
          .fontSize(12)
          .text(
            `Candidate ID: ${reportData.candidate}`
          );

        /*
        SCORES
        */

        doc.moveDown();

        doc
          .fontSize(18)
          .text(
            "Competency Scores"
          );

        doc.moveDown(0.5);

        Object.entries(
          reportData.scores
        ).forEach(
          ([key, value]) => {
            doc.text(
              `${key}: ${value}%`
            );
          }
        );

        /*
        RECOMMENDATION
        */

        doc.moveDown();

        doc
          .fontSize(18)
          .text(
            "Hiring Recommendation"
          );

        doc.moveDown(0.5);

        doc.text(
          reportData
            .recommendation
            .recommendation
        );

        doc.text(
          reportData
            .recommendation
            .reason
        );

        /*
        STRENGTHS
        */

        doc.moveDown();

        doc
          .fontSize(18)
          .text("Strengths");

        reportData.analytics.strengths.forEach(
          (
            strength
          ) => {
            doc.text(
              `• ${strength}`
            );
          }
        );

        /*
        IMPROVEMENTS
        */

        doc.moveDown();

        doc
          .fontSize(18)
          .text(
            "Improvement Areas"
          );

        reportData.analytics.improvements.forEach(
          (
            improvement
          ) => {
            doc.text(
              `• ${improvement}`
            );
          }
        );

        /*
        ANSWERS
        */

        doc.addPage();

        doc
          .fontSize(20)
          .text(
            "Interview Analysis"
          );

        doc.moveDown();

        reportData.answers.forEach(
          (
            answer,
            index
          ) => {
            doc
              .fontSize(14)
              .text(
                `Q${index + 1}: ${answer.question}`
              );

            doc.moveDown(
              0.3
            );

            doc
              .fontSize(11)
              .text(
                `Answer: ${answer.answer}`
              );

            doc.moveDown(
              0.3
            );

            doc.text(
              `Score: ${answer.evaluation.overallScore}%`
            );

            doc.text(
              `Feedback: ${answer.evaluation.feedback}`
            );

            doc.moveDown();
          }
        );

        /*
        FOOTER
        */

        doc.moveDown(2);

        doc
          .fontSize(10)
          .text(
            "Generated by AI Powered Resume Competency Verification System",
            {
              align:
                "center",
            }
          );

        /*
        FINALIZE
        */

        doc.end();

        stream.on(
          "finish",

          () => {
            resolve(
              filePath
            );
          }
        );

        stream.on(
          "error",

          reject
        );
      }
    );
  };